ruleset=🔎 DNS,https://raw.githubusercontent.com/Simon4m/clash/main/Dns.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📲 Threema,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Threema.list
ruleset=📲 Whatsapp,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/WhatsApp.list
ruleset=📲 Whatsapp,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Whatsapp.list
ruleset=📲 Twitter,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Twitter.list
ruleset=📲 Twitter,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=📲 TeamViewer,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TeamViewer.list
ruleset=📲 Threads,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Threads.list
ruleset=📲 Threads,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Threads/Threads.list
ruleset=📲 Instagram,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Instagram.list
ruleset=📲 Instagram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.list
ruleset=📲 Facebook,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Facebook.list
ruleset=📲 Facebook,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.list
ruleset=📲 Line,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Line.list
ruleset=📲 Line,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list
ruleset=📲 Discord,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Discord.list
ruleset=📲 Discord,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.list
ruleset=📲 Medium,https://raw.githubusercontent.com/Simon4m/clash/main/Medium.list
ruleset=📲 Reddit,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Reddit.list
ruleset=📲 Reddit,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Reddit.list
ruleset=📲 Dcard,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Dcard.list
ruleset=📲 Dcard,https://raw.githubusercontent.com/Simon4m/clash/main/Dcard.list
ruleset=📲 Mobile01,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Mobile01.list
ruleset=📲 Mobile01,https://raw.githubusercontent.com/Simon4m/clash/main/mobile01.list
ruleset=📲 Coolapk,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Coolapk.list
ruleset=📲 Coolapk,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Coolapk/Coolapk.list
ruleset=📲 Weibo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.list
ruleset=📲 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📲 TikTok,https://raw.githubusercontent.com/Simon4m/clash/main/tiktok.list
ruleset=📲 Tiktok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.list
ruleset=📲 Zhihu,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Zhihu/Zhihu.list
ruleset=📲 支那書,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Xiaohongshu.list
ruleset=📲 支那書,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=📲 Fcmwx,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/Fcmwx.list
ruleset=📲 WeChat,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Wechat.list
ruleset=📲 WeChat,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
ruleset=📲 Ultramobile,https://raw.githubusercontent.com/Simon4m/clash/main/Ultramobile.list
ruleset=🏦 Zimperium,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/Zimperium.list
ruleset=🏦 Binance,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Binance.list
ruleset=🏦 Binance,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Binance/Binance.list
ruleset=🏦 IfastGB,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/iFastGB.list
ruleset=🏦 IfastGB,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/IFASTGB.list
ruleset=🏦 Paypal,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Paypal.list
ruleset=🏦 Paypal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
ruleset=🛍️ Shoppe,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopee/Shopee.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🎶 YouTubeMusic,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=🎶 TIDAL,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TIDAL.list
ruleset=🎶 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🎶 Kkbox,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/KKBOX.list
ruleset=🎶 Headphones,https://raw.githubusercontent.com/Simon4m/clash/main/Headphones.list
ruleset=🎶 Sony,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🎞️ Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎞️ HamiVideo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HamiVideo/HamiVideo.list
ruleset=🎞️ FKNF,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/FKNF.list
ruleset=🎞️ Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎞️ HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Gamer.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=📺 Niconico,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Niconico.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Twitch,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitch.list
ruleset=💻 Github,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🍎 Apns,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/Apns.list
ruleset=📢 FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🔎 Wikipedia,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Wikimedia/Wikimedia.list
ruleset=🔎 Earth,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleEarth/GoogleEarth.list
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=💻 Claude,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/Claude.list
ruleset=💻 Claude,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/Claude.list
ruleset=💻 OpenAI,https://raw.githubusercontent.com/Simon4m/PROCESS/refs/heads/main/ChatGPT.list
ruleset=💻 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🔍 Yahoo,https://raw.githubusercontent.com/Simon4m/clash/main/Yahoo.list
ruleset=🔍 News,https://raw.githubusercontent.com/Simon4m/clash/main/News.list
ruleset=Ⓜ️ Winup,https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/win-update.txt
ruleset=Ⓜ️ Wintest,https://raw.githubusercontent.com/Simon4m/clash/main/Wintest.list
ruleset=Ⓜ️ Edge,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MicrosoftEdge/MicrosoftEdge.list
ruleset=🎮 Xbox,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=Ⓜ️ Lenovo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lenovo/Lenovo.list
ruleset=Ⓜ️ Nvidia,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nvidia/Nvidia.list
ruleset=Ⓜ️ AMD,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/AMD/AMD.list
ruleset=🍎 AppleOTA,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SystemOTA/SystemOTA.list
ruleset=🎶 Apple Music,https://raw.githubusercontent.com/Simon4m/clash/main/AppleMusic.list
ruleset=🍎 iCloud,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloud/iCloud.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🌐 Samsung,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Samsung/Samsung.list
ruleset=🌐 Speedtest,https://raw.githubusercontent.com/MengXIFyluy/clash/main/Speedtest.list
ruleset=🌐 Exitlag,https://raw.githubusercontent.com/Simon4m/clash/main/Exitlag.list
ruleset=🎮 Steamcdn,https://raw.githubusercontent.com/Simon4m/clash/main/Steamcdn.list
ruleset=🎮 CS2,https://raw.githubusercontent.com/Simon4m/clash/main/CS2.list
ruleset=🎮 GTAV,https://raw.githubusercontent.com/Simon4m/clash/main/GTAV.list
ruleset=🎮 CNSteam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/Simon4m/clash/main/Steam.list
ruleset=🎮 Steam,[]geosite,steam
ruleset=🎮 Steam,[]geoip,steam
ruleset=🎮 EA,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🎮 Epic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🎮 Ubisoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=🎮 Rockstar,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Rockstar/Rockstar.list
;ruleset=🎮 CSGO,https://raw.githubusercontent.com/Simon4m/clash/main/CSGO.list
;ruleset=🎮 L4D2,https://raw.githubusercontent.com/Simon4m/clash/main/L4D2.list
;ruleset=🎮 Dead-by-Daylight,https://raw.githubusercontent.com/Simon4m/clash/main/Dead-by-Daylight.list
ruleset=🎮 MahjongSoul,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Majsoul/Majsoul.list
;ruleset=🎮 Weplay,https://raw.githubusercontent.com/Simon4m/clash/main/Weplay.list
ruleset=📲 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🇨🇳 FKOPPO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OPPO/OPPO.list
ruleset=🇨🇳 FKMIUI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/MIUIPrivacy/MIUIPrivacy.list
;ruleset=🎶 網易雲音樂,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🇨🇳 支那Misc,https://raw.githubusercontent.com/Simon4m/clash/refs/heads/main/FkChinamatch.list
ruleset=🇹🇼 中華民國,https://raw.githubusercontent.com/Simon4m/clash/main/Taiwan.list
ruleset=🇹🇼 中華民國,[]GEOIP,TW
ruleset=🇺🇸 美國,[]GEOIP,US
ruleset=🇭🇰 HK,[]GEOIP,HK
ruleset=🌐 Tencent,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.list
;ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs.list
ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🇨🇳 支那牆國,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🇨🇳 支那牆國,[]GEOIP,LAN
ruleset=🇨🇳 支那牆國,[]GEOIP,CN
ruleset=🇨🇳 支那牆國,[]GEOSITE,CN
ruleset=🐟 Match,[]FINAL
